apiVersion: v1
kind: ConfigMap
metadata:
  name: java-swing-tutor-config
  namespace: java-swing-tutor
data:
  db.url: "jdbc:postgresql://shared-posadskiy.e.aivencloud.com:25370/java_swing_tutor_db?sslmode=require"
  db.user: "avnadmin"
